version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: santacasa/sistema-assinaturas-backend:latest
    container_name: sistema-assinaturas-backend
    ports:
      - "4000:4000"
    networks:
      - sistema-assinaturas-network
    restart: always
    environment:
      # Configurações do Banco de Dados PostgreSQL
      DB_HOST: notasfiscais_db
      DB_PORT: 5432
      DB_NAME: notasfiscais_db   # Use o mesmo nome do banco configurado no PostgreSQL
      DB_USER: postgres
      DB_PASSWORD: postgres

    depends_on:
      - postgres

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: santacasa/sistema-assinaturas-frontend:latest
    container_name: sistema-assinaturas-frontend
    ports:
      - "5000:5000"
    networks:
      - sistema-assinaturas-network
    restart: always

  postgres:
    image: postgres:15
    container_name: notasfiscais_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: notasfiscais_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # Certifique-se de que a senha aqui é a mesma no backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sistema-assinaturas-network

networks:
  sistema-assinaturas-network:
    driver: bridge

volumes:
  postgres_data:
