# Docker Compose para PostgreSQL

services:
  postgres:
    image: postgres:15
    container_name: notasfiscais_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: notasfiscais_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - notasfiscais_network

  # Opcional: pgAdmin para gerenciar o banco
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: notasfiscais_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@empresa.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - notasfiscais_network

volumes:
  postgres_data:

networks:
  notasfiscais_network:
    driver: bridge
